unpackbootimg: reversion needed for -m32 on gcc 11.x
unpackbootimg.c:301:52: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Werror=format=]

Seems the solution in #14 doesn't hold for -m32 on gcc 11.x, so revert back to older CM solution which does (ref: https://github.com/osm0sis/mkbootimg/pull/14#issuecomment-819941402)